language: android
android:
  components:
  - build-tools-$BUILD_TOOL
  - android-$ANDROID_API
  - extra-android-m2repository
before_script:
  - echo TELEGRAM_WEBHOOKS=$TELEGRAM_WEBHOOKS >> .env
  - echo GIT_REPO=$TRAVIS_REPO_SLUG >> .env
  - echo GIT_BRANCH=$TRAVIS_BRANCH >> .env
install:
  - rvm install 2.3.4
  - gem install fastlane
after_success:
  - "./ci/deploy.sh"
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
env:
  global:
  - BUILD_TOOL=22.0.1
  - ANDROID_API=22
  - secure: AWlCndEn3Aiax6wEMp392YiWyzm1cy+olTvEx176ww6FWXc2Gwu1znauXcGkcCEB1d9V0t/6osCSKHtZssEtddPvBkavMEw45W45PylTVJFE3MBQmTUy9wLIKQll2+1LhrVPkjMBMKHFprqgkuDZ78cs2B3EgGvejYt+8D298PseaEmkSo4zWD0AwAwVJ8jJQC2A48lN1Hx9bewRE4pTW9KGh87z4GmcX/pADzkAEIZ2SrZj5msH6ghGoFUlKCE5VpjO8iKrI6i4PTbxBylJQsbpNvwnbuWN0sQaeMjQqjAokx6UpzX9YNyJPt2rWvJnwjUF3Up0TltU1avKr14Jv3pgizFi95/W10AEj9l0VuQxdWXOgIeuCUmbvmD2BQw6IX3v4qzoorw888W53bJGYy9W1XNbUJ+5KOzVkbZjr3AtjuX8v0PSmP/gqDkWTIEeUTP9btHYajAfIpPunedHe+g7mZ9APTfyagAof8+AKlVNzt/5l40Fn+iQ9dNijwDDKOVzzSHFUplv8YKbCibN4Rsq2S2liWZqPJYyE2xRPtn5XlqDM2w/Q6c4fMbknXjfAtwXKhDBH8u9mMX9z8tjWxVQpUUtOx4FRREwC1V5ongvzsyzEMLDZrwnChvDZz6P4OgegSxwhZhAnwk3Rmd9W8sa9mrkBcvnFHheC01rCZY=
  - secure: aoYBJcY4gpvfeTtPmu5j5Vr+rt+7RnsZeWwl0z5iSIty+M8eSA+p3B4JHOQoa90aW+eLZIgA/XsnJUm5+wOGjlz8BGPdAyVVlMBF4qrAJKj12fP+M1n+AK59N+wuN+m9EraXlCf2JE2Ty1ioaxWhWlauFI4Ihw5hY6QKHot4frtNq7VCiJ9kQWSFMrIrSJTMAQNZG7wfweGE/CUKSHWeJ/L/YFvbLRjgYEcqkG4lDWYt/noDCElu1OFLKeFiPYVhxrDMf4H+HsxPQYu61H8JKtOFaiusjcEpvvOAlCX1kzM0wsMK4U846nUw+WENd36WMN6YcWiP5CtHt0vOloyhOLVHWELSUbLfw+TRtT+HeOZ/jxueQ8BfLygj6Pb5TClKLK3ENlrqTlafT4PMgMZNsLQ3e0++UJoyRKrHleFArzqR+Bk6MN3xibZAkiy1DPidjQPLvmuSmoACvcjnr5h4etli9bdUo50UagbRORSxCLItn3JePHwlNpLvKEld5zSK0C5lPexCAbLFVAhVw1pO5CCHJeX4FuSbdIhiOsY8GmZg6ZAccgW91tDyhtijwmf1NxiGr+0PcHCHl92jg+U4RgQTmInveOnStRYpEOO+MJaInfuQkxrY+PJbnlR37/QtjOX6lsVcv0c7nfp0BA0IWK4sg3DEdI2D8jBbVgwYS58=
  - secure: sbkupB3RV/3g9E74jVAlW0s0ocGqZci2rmhPuqFQMt4siDzfoHcgT0trwfYWW1SflCEI/v9rkjSVob6sefc1caKd+OD0Ds/2eN8QMj/wglWgxzS8sdKs/E8qzkg9QO9GRImRVxvK3wjegj4bSbErkGo3SrjHfPrsYeEFBYCNqgzsvo3nz+l58/aOB2VZYrsAOBOn8rEhb1LETvCT+G2mPe7JMXGQMLZ9lPc4Zkcc1YDjlCLCuz8EouZUtfmh0jMEW5vZ6WN8pKU8Zoj0S1vGWY+ndTp9lhxamcPiCxnvFuRe0GUM08KaWlujahcCjaDB6TfAgrTKsNMSQW7KI+FBCt30k5bUDw9g0u3rpWoZLT6/u/u3ExmonGPGs0HA92nytOIumymjd/DT5h0K8gSkOoqQ9oF8H/C6Z1qnnU6kEqjlFAy+qdM5uDmum/k5cUsZR8JwN6TnictaJ/gzMXB2fxoDeCtgiU1KPbVNasp9wjfCJjvcUu2k6IvppZHaOUdG8JKmqbzKtmiv1XqltPK950GSS3+jVAjQkthwMf3WJ4HNV/Hnrfn4MowDA2bDipDgmDSPmVBuIjs9JnCQYRQY0OVhtupj6PXyyX6P2kOaRxKr+62wtJqINec/qntJ7X6pjiLRDBteAs4Vc++3A57uSZDfE1eXBG2jwHaRjRL9TkY=
before_install:
- openssl aes-256-cbc -K $encrypted_fbe35f3d891b_key -iv $encrypted_fbe35f3d891b_iv
  -in google.tar.gz.enc -out ci/google.tar.gz -d
