version: 2
reference:

  ## Workspaces
  workspace: &workspace
    ~/flyve_mdm

  ## Docker image configurations
  android_config: &android_config
    working_directory: *workspace
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m"'

  ## Cache
  gradle_key: &gradle_key
    jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

  gems_key: &gems_key
    gems-{{ checksum "Gemfile.lock" }}

  restore_gradle_cache: &restore_gradle_cache
    restore_cache:
      key: *gradle_key

  restore_gems_cache: &restore_gems_cache
    restore_cache:
      key: *gems_key

  save_gradle_cache: &save_gradle_cache
    save_cache:
      key: *gradle_key
      paths:
        - ~/.gradle
        - ~/.m2

  save_gems_cache: &save_gems_cache
    save_cache:
      key: *gems_key
      paths:
        - vendor/bundle

  ## Dependencies
  ruby_dependencies: &ruby_dependencies
    run:
      name: Download Ruby Dependencies
      command: bundle check || bundle install --path vendor/bundle

  android_dependencies: &android_dependencies
    run:
      name: Download Android Dependencies
      command: ./gradlew androidDependencies

jobs:
  # simple build
  build:
    <<: *android_config
    steps:
      - checkout
      - *restore_gradle_cache
      - *restore_gems_cache
      - *ruby_dependencies
      - *android_dependencies
      - *save_gradle_cache
      - *save_gems_cache

  # Test Instrumentation with Android 4.1 JELLY_BEAN API 16
  test_instrumentation:
    <<: *android_config
    steps:
      - checkout
      - *restore_gradle_cache
      - *restore_gems_cache
      - *ruby_dependencies
      - *android_dependencies
      - *save_gradle_cache
      - *save_gems_cache
      - run:
          name: Create debug apk
          command: ./gradlew assembleDebug
      - run:
          name: Run Tests
          command: source ci/scripts/google_cloud.sh
      - store_artifacts:
          path: firebase/
          destination: /firebase/

  deploy_beta:
    <<: *android_config
    steps:
      - checkout
      - *restore_gradle_cache
      - *restore_gems_cache
      - *ruby_dependencies
      - *android_dependencies
      - *save_gradle_cache
      - *save_gems_cache
      - run:
          name: Setup environment
          command: source ci/scripts/setup_environment.sh
      - run:
          name: Deploy Beta
          command: source ci/scripts/flow_beta.sh

  deploy_production:
    <<: *android_config
    steps:
      - checkout
      - *restore_gradle_cache
      - *restore_gems_cache
      - *ruby_dependencies
      - *android_dependencies
      - *save_gradle_cache
      - *save_gems_cache
      - run:
          name: Setup environment
          command: source ci/scripts/setup_environment.sh
      - run:
          name: Deploy Production
          command: source ci/scripts/flow_production.sh

  documentation:
    <<: *android_config
    steps:
      - checkout
      - *restore_gradle_cache
      - *restore_gems_cache
      - *ruby_dependencies
      - *android_dependencies
      - *save_gradle_cache
      - *save_gems_cache
      - run:
          name: Generate Documentation
          command: source ci/scripts/create_documentation.sh

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test_instrumentation:
          requires:
            - build
          filters:
            branches:
              ignore:
                - master
      - deploy_beta:
          requires:
            - test_instrumentation
          filters:
            branches:
              only:
                - develop
      - documentation:
          requires:
            - test_instrumentation
          filters:
            branches:
              only:
                - develop
      - deploy_production:
          requires:
            - build
          filters:
            branches:
              only:
                - master