version: 2
reference:

  ## Workspaces
  workspace: &workspace
    ~/flyve_mdm

  ## Docker image configurations
  android_config: &android_config
    working_directory: *workspace
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m"'

  ## Cache
  gradle_key: &gradle_key
    jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

  gems_key: &gems_key
    gems-{{ checksum "Gemfile.lock" }}

  restore_gradle_cache: &restore_gradle_cache
    restore_cache:
      key: *gradle_key

  restore_gems_cache: &restore_gems_cache
    restore_cache:
      key: *gems_key

  save_gradle_cache: &save_gradle_cache
    save_cache:
      key: *gradle_key
      paths:
        - ~/.gradle
        - ~/.m2

  save_gems_cache: &save_gems_cache
    save_cache:
      key: *gems_key
      paths:
        - vendor/bundle

  ## Dependencies
  ruby_dependencies: &ruby_dependencies
    run:
      name: Download Ruby Dependencies
      command: bundle check || bundle install --path vendor/bundle

  android_dependencies: &android_dependencies
    run:
      name: Download Android Dependencies
      command: ./gradlew androidDependencies

  ## Simulator
  emulator_setup_16: &emulator_setup_16
    run:
      name: Setup emulator
      command: sdkmanager "system-images;android-16;default;armeabi-v7a" && echo "no" | avdmanager create avd -n device -k "system-images;android-16;default;armeabi-v7a"

  emulator_launch: &emulator_launch
    run:
      name: Launch emulator
      command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd device -noaudio -no-boot-anim -no-window -accel on
      background: true

  emulator_wait: &emulator_wait
    run:
      name: Wait emulator
      command: |
        # wait for it to have booted
        circle-android wait-for-boot
        # unlock the emulator screen
        sleep 30
        adb shell input keyevent 82


jobs:
  # simple build
  build:
    <<: *android_config
    steps:
      - checkout
      - *restore_gradle_cache
      - *restore_gems_cache
      - *ruby_dependencies
      - *android_dependencies
      - *save_gradle_cache
      - *save_gems_cache

  # Test Instrumentation with Android 4.1 JELLY_BEAN API 16
  test_instrumentation_16:
    <<: *android_config
    steps:
      - checkout
      - *restore_gradle_cache
      - *restore_gems_cache
      - *ruby_dependencies
      - *android_dependencies
      - *save_gradle_cache
      - *save_gems_cache
      - *emulator_setup_16
      - *emulator_launch
      - *emulator_wait
      - run:
          name: Run Tests
          command: ./gradlew connectedAndroidTest
      - store_artifacts:
          path: app/build/reports/
          destination: /reports/
      - store_test_results:
          path: app/build/test-results/
          destination: /test-results/

  # Screen capture
  screenshot_api_16:
    <<: *android_config
    steps:
      - checkout
      - *restore_gradle_cache
      - *restore_gems_cache
      - *ruby_dependencies
      - *android_dependencies
      - *save_gradle_cache
      - *save_gems_cache
      - *emulator_setup_16
      - *emulator_launch
      - *emulator_wait
      - run:
          name: Setup environment
          command: source ci/scripts/ci_setup.sh
      - run:
          name: Update about information
          command: source ci/scripts/ci_about.sh
      - run:
          name: Assemble Android Tests
          command: ./gradlew assembleDebug assembleAndroidTest
      - run:
          name: Run Fastlane Screengrab
          command: fastlane screengrab
      - run:
          name: send screenshot to gh-pages
          command: source ci/scripts/ci_push_screenshot.sh
      - store_artifacts:
          path: fastlane/metadata
          destination: screenshot

  deploy_beta:
    <<: *android_config
    steps:
      - checkout
      - *restore_gradle_cache
      - *restore_gems_cache
      - *ruby_dependencies
      - *android_dependencies
      - *save_gradle_cache
      - *save_gems_cache
      - run:
          name: Setup environment
          command: source ci/scripts/ci_setup.sh
      - run:
          name: Deploy Beta
          command: source ci/scripts/ci_flow_beta.sh

  deploy_production:
    <<: *android_config
    steps:
      - checkout
      - *restore_gradle_cache
      - *restore_gems_cache
      - *ruby_dependencies
      - *android_dependencies
      - *save_gradle_cache
      - *save_gems_cache
      - run:
          name: Setup environment
          command: source ci/scripts/ci_setup.sh
      - run:
          name: Deploy Production
          command: source ci/scripts/ci_flow_production.sh

  documentation:
    <<: *android_config
    steps:
      - checkout
      - *restore_gradle_cache
      - *restore_gems_cache
      - *ruby_dependencies
      - *android_dependencies
      - *save_gradle_cache
      - *save_gems_cache
      - *emulator_setup_16
      - *emulator_launch
      - *emulator_wait
      - run:
          name: Generate Documentation
          command: source ci/scripts/ci_documentation.sh

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test_instrumentation_16:
          requires:
            - build
          filters:
            branches:
              ignore:
                - master
      - deploy_beta:
          requires:
            - test_instrumentation_16
          filters:
            branches:
              only:
                - develop
      - documentation:
          requires:
            - test_api_v16
          filters:
            branches:
              only:
                - develop
      - screenshot_api_16:
          requires:
            - test_api_v16
          filters:
            branches:
              only:
                - develop
      - deploy_production:
          requires:
            - build
          filters:
            branches:
              only:
                - master